name: CI

on:
  push:
    branches:
      - '**'

permissions:
  contents: read
  id-token: write

jobs:
  build:
    uses: ngocdanthanhtvu/hicommit-runner/.github/workflows/c-runner.yml@b1aa0f53904808b88555f8782dc01b4489b9bd75
