name: CI

on:
  push:
    branches:
      - '**'

permissions:
  contents: read
  id-token: write

jobs:
  build:
    uses: ngocdanthanhtvu/hicommit-runner/.github/workflows/c-runner.yml@15729cc8418e268324feda69f27327eaf0975bf9
