name: CI

on:
  push:
    branches:
      - '**'

permissions:
  contents: read
  id-token: write

jobs:
  build:
    uses: ngocdanthanhtvu/hicommit-runner/.github/workflows/c-runner.yml@09905f928b847d5e728cede9534bd335cf86c887
    with:
      api_base_url: https://turbo-fortnight-xg7pwq7j4vxfjg-5174.app.github.dev
